### PR TITLE
Add support for array arguments

### LINKED ISSUE #3: TypeError: Path must be a string
The document says 
`cwd(['one', 'two.js']);`

but we got

```
> cwd(['one', 'two.js'])
TypeError: Path must be a string. Received [ 'one', 'two.js' ]
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1148:7)
    at module.exports (/Users/skyline/.trymodule/node_modules/cwd/index.js:28:23)
    at repl:1:1
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at REPLServer.defaultEval (repl.js:308:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:489:10)
    at emitOne (events.js:101:20)
```

### PR DESCRIPTION
**Pull request by lcjnil**
resolve #3

### CODE REVIEW

**Comment by lcjnil** [comment]
@jonschlinkert  any recent news?

**Comment by jonschlinkert** [comment]
thanks I'll merge and publish asap!

**Comment by NetOpWibby** [comment]
Is this gonna get merged?

**Comment by jonschlinkert** [comment]
> Is this gonna get merged?

No, I misspoke when I when I said I would merge. In the linked issue I said that this was a documentation problem, the code doesn't need to change.

**Pull request closed without merging**
